### ISSUE TITLE
Use reflow on layout to make it more mobile-friendly

### ISSUE THREAD

**Issue by eadgbear** [upsuper/rust-cheatsheet#1]
It would be great if the sections were in (possibly collapsible) flowing sections so that or smaller layouts can view the sections more easily.

**Comment by TheSirC** [comment]
I double down on this. I would use it 24/7 if mobile friendly.
I use this occasion to thank you for your work with mixed tears of joy and resentment (was working on the same type of project but yours is orders of magnitude better; thanks for the good work!)

**Comment by upsuper** [comment]
I add some initial support of a single column mode to the page. You can enable it via adding `?single` to the url: https://upsuper.github.io/rust-cheatsheet/?single

I also add a large mode, which can be combined with single mode: https://upsuper.github.io/rust-cheatsheet/?single,large

I'll probably try to add a link or so in the footer for them later.

**Comment by eadgbear** [comment]
Fantastic, thanks!

**Comment by upsuper** [comment]
Link is added in cf605571b062389a3fd1c15d34bc1c2611b602b3. Closing now.
